include:
  - project: 'dgsys/k8s/isp-ci-templates'
    ref: 'master'
    file: 'application/docker/kaniko.yml'

variables:
  IMAGE_NAME: ${DOCKER_CI_REGISTRY}/${CI_PROJECT_NAME}

build-image:
  before_script: 
    - echo "{\"auths\":{\"${DOCKER_CI_REGISTRY}\":{\"username\":\"${DOCKER_CI_USER}\",\"password\":\"${DOCKER_CI_PASSWORD}\"}}}" > /kaniko/.docker/config.json
  extends: .kaniko-build-template
  when: manual
  only:
    - pre-release
  tags:
    - isppd
